insert into Class(classroom_id, staff_id, course_id, class_name, tutorial_group)
    values
        (5, 2, 1, 'Economics', 'G2'),
        (5, 3, 1, 'Economics', 'G3'),
        (5, 4, 1, 'Economics', 'G4'),
        (5, 5, 1, 'Economics', 'G5'),
        (5, 6, 1, 'Economics', 'G6'),
        (4, 7, 1, 'Global Business', 'H1'),
        (4, 1, 1, 'Global Business', 'H2'),
        (4, 2, 1, 'Global Business', 'H3'),
        (3, 8, 1, 'Makings of a Business', 'I4'),
        (3, 8, 1, 'Makings of a Business', 'I6'),
        (3, 6, 1, 'Makings of a Business', 'I8'),
        (11, 6, 1, 'Programming for Business', 'P'),
        (11, 10, 1, 'Statistical Applications for Business', 'Q'),
        (11, 12, 1, 'Health & Wellness', 'A'),
        (2, 4, 1, 'Innovation Made Possible', 'B2'),
        (2, 5, 1, 'Innovation Made Possible', 'B3'),
        (2, 7, 1, 'Innovation Made Possible', 'B4'),
        (1, 12, 1, 'English Language Express', 'E1'),
        (1, 13, 1, 'English Language Express', 'E2'),
        (1, 14, 1, 'English Language Express', 'E3'),
        (2, 1, 1, 'Business Communication 1', 'B1'),
        (10, 3, 1, 'Business Communication 1', 'B2'),
        (8, 4, 1, 'Business Communication 1', 'B3'),
        (11, 15, 1, 'Business Law', 'C'),
        (2, 20, 1, 'Kickstart a Business', 'K1'),
        (2, 18, 1, 'Kickstart a Business', 'K2'),
        (2, 14, 1, 'Kickstart a Business', 'K3'),
        (2, 12, 1, 'Finance & Accounting for Business', 'F1'),
        (5, 13, 1, 'Finance & Accounting for Business', 'F3'),
        (5, 1, 1, 'Finance & Accounting for Business', 'F5'),
        (3, 3, 1, 'User-Centred Design for Business', 'U1'),
        (2, 14, 1, 'User-Centred Design for Business', 'U3'),
        (2, 17, 1, 'User-Centred Design for Business', 'U5'),
        (11, 22, 1, 'Career & Professional Preparation', 'C'),
        (11, 21, 1, 'Company Law & Secretarial Practice', 'L'),
        (2, 3, 1, 'Digitalisation & Data Analytics 1', 'D1'),
        (5, 2, 1, 'Digitalisation & Data Analytics 1', 'D4'),
        (5, 2, 1, 'Digitalisation & Data Analytics 1', 'D5'),
        (11, 28, 1, 'Financial Accounting', 'F'),
        (11, 29, 1, 'Singapore Taxation', 'T'),
        (11, 24, 1, 'World Issues: A Singapore Perspective', 'W'),
        (11, 20, 1, 'Assurance, Risk & Forensic Accounting', 'A'),
        (2, 5, 1, 'Business Communication 2', 'B1'),
        (2, 6, 1, 'Business Communication 2', 'B2'),
        (5, 4, 1, 'Business Communication 2', 'B4'),
        (5, 7, 1, 'Corporate Reporting', 'CR2'),
        (6, 8, 1, 'Corporate Reporting', 'CR3'),
        (6, 2, 1, 'Corporate Reporting', 'CR4'),
        (5, 4, 1, 'Digitalisation & Data Analytics 2', 'DDA1'),
        (6, 5, 1, 'Digitalisation & Data Analytics 2', 'DDA2'),
        (4, 2, 1, 'Digitalisation & Data Analytics 2', 'DDA3'),
        (11, 23, 1, 'Advanced Corporate Reporting & Sustainability', 'ACRS'),
        (11, 12, 1, 'Corporate Finance', 'CF'),
        (5, 19, 1, 'Decision-Making & Control for Business', 'DM1'),
        (5, 19, 1, 'Decision-Making & Control for Business', 'DM2'),
        (3, 21, 1, 'Decision-Making & Control for Business', 'DM3'),
        (3, 21, 1, 'Decision-Making & Control for Business', 'DM4'),
        (3, 12, 1, 'Project ID: Connecting The Dots', 'PID-DOTS1'),
        (3, 12, 1, 'Project ID: Connecting The Dots', 'PID-DOTS2'),
        (11, 24, 1, 'Ethics for the Professional Accountant', 'ETH'),
        (5, 12, 1, 'Advanced Applied Business Analytics', 'AABA3'),
        (5, 12, 1, 'Advanced Applied Business Analytics', 'AABA4'),
        (4, 2, 1, 'Advanced Applied Business Analytics', 'AABA5'),
        (2, 3, 1, 'Artificial Intelligence & Robotics', 'AIR2'),
        (2, 5, 1, 'Artificial Intelligence & Robotics', 'AIR4'),
        (11, 3, 1, 'Digital Transformation Marketing Strategy', 'DTMS'),
        (11, 4, 1, 'Emerging Technologies & Disruptive Innovation', 'ETDI'),
